version: '3'

services: 
  whereto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080

  seq:
    image: datalust/seq:latest
    container_name: whereto-seq
    environment:
      - ACCEPT_EULA=Y 
    ports:
      - 5341:5341
      - 8081:80