name: Build and Test with Docker

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image and export test results
        run: |
          docker build --target export-test-results --output type=local,dest=out .

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: exported-test-results
          path: out

      - name: Docker build WhereTo image
        run:
          docker build -t whereto:latest -f Dockerfile .
          
      - name: Docker build BookingService image
        run:
          docker build -t bookingservice:latest -f BookingServiceDockerfile .
